### PR TITLE
[Build docs] Move to a unified build, fix doc builds

### LINKED ISSUE #14: Documentation publishing pipeline is broken
https://github.com/llvm/circt-www/actions/workflows/main.yml e.g. https://github.com/llvm/circt-www/actions/runs/4570251709/jobs/8067377169

The documentation PR (https://github.com/llvm/circt/pull/4888) I merged on Monday didn't make it up to circt.llvm.org. This is probably the reason why. Looks like it's been broken since Jan 27th.

### PR DESCRIPTION
**Pull request by teqdruid**
Fixes #14. Switching to a unified build to both save _a lot_ of compile time and fix the LLVM build (by not building everything). Also switches from make to ninja since ninja is what's recommended.

### CODE REVIEW

**Comment by teqdruid** [comment]
Proof build: https://github.com/teqdruid/circt-www/actions/runs/4579679373/jobs/8087692187 .  everything passed except for deploy.

**Comment by teqdruid** [comment]
Dunno who has approve and merge perms. @drom ?

**Review by mikeurbach — APPROVED** [review]
Works for me. I guess we could add back caching, but not necessary.

**Comment by mikeurbach** [comment]
Looks like I have write access.

**Comment by teqdruid** [comment]
Thanks!

**Comment by teqdruid** [comment]
> Works for me. I guess we could add back caching, but not necessary.

Yeah, it only compiles ~300 files so I don't think it's necessary. That's down from >4000 previously.

**Pull request merged**
